data:
    - name: db1
      url: jdbc:mysql://localhost:3306/study?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 123456
    - name: db2
      url: jdbc:mysql://localhost:3306/temp1?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 123456
    - name: db3
      url: jdbc:mysql://localhost:3306/temp2?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

spring:
  cache:
    type: redis    #指定使用redis作为缓存
  data:
    redis:
      database: 0         # Redis数据库索引（默认为0）
      timeout: 60000      # 连接超时时间（毫秒）
      port: 6379
      lettuce:
        shutdown-timeout: 100    # 毫秒
        pool:
          min-idle: 5    # 连接池中的最小空闲连接
          max-active: 5000  # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 10  # 连接池中的最大空闲连接
          max-wait: 1000   # 连接池最大阻塞等待时间（使用负值表示没有限制）:毫秒
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/study?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8&allowMultiQueries=true
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver

